name: workout_tracker
description: A private, offline-capable workout tracker app for personal use.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite_sqlcipher: ^3.2.0
  path: ^1.8.3
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  fl_chart: ^1.0.0
  intl: ^0.20.0
  
  # Data Export/Import
  path_provider: ^2.1.1
  share_plus: ^11.0.0
  file_picker: ^8.0.0
  
  # Permissions
  permission_handler: ^12.0.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  
  # URL Launcher
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/ 